version: '2'
services:
    app:
        environment:
            - TZ=America/Chicago
        image: node:14.8.0
        hostname: node-app
        volumes:
            - ./app:/usr/src/app
        command: ['node', '/usr/src/app/index.js']
