version: '2'
services:
    app:
        image: node:8.2.1
        hostname: node-app
        volumes:
            - ./app:/usr/src/app
            - ./app/.env:/usr/src/app/.env
        command: ['node', '/usr/src/app/index.js']
